version: "3.6"

#docker-compose.override.yml is loaded and merged with docker-compose.yml by default when calling docker-compose up.
#This file won't be merged when using docker-compose -f docker-compose.yml up (or using any other compose file).
services:

  load_s3:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
    volumes:
      - ./migration_steps/load_s3/load_s3_local.py:/load_s3_local.py
      - ./migration_steps/load_s3/synchronise_s3.py:/synchronise_s3.py
      - ./migration_steps/load_s3/local_s3.sh:/local_s3.sh

  prepare:
    volumes:
      - ./migration_steps/prepare/prepare.sh:/prepare/prepare.sh
      - ./migration_steps/prepare/prepare_target:/prepare/prepare_target
      - ./migration_steps/prepare/create_stage_schema:/prepare/create_stage_schema
      - ./migration_steps/shared:/shared

  load_casrec:
    volumes:
      - ./migration_steps/load_casrec/app:/app

  transform_casrec:
    volumes:
      - ./migration_steps/transform_casrec/app/:/app
      - ./migration_steps/shared:/shared

  integration:
    volumes:
      - ./migration_steps/integration/fixtures:/integration/fixtures
      - ./migration_steps/integration/schema_setup:/integration/schema_setup
      - ./migration_steps/integration/load_to_staging:/integration/load_to_staging
      - ./migration_steps/integration/integration.sh:/integration/integration.sh
      - ./migration_steps/integration/reindex_ids:/integration/reindex_ids
      - ./migration_steps/integration/business_rules:/integration/business_rules
      - ./migration_steps/shared:/shared

  load_to_target:
    volumes:
      - ./migration_steps/load_to_sirius:/load_to_sirius
      - ./migration_steps/shared:/shared

  validation:
    volumes:
      - ./migration_steps/validation/api_tests:/validation/api_tests
      - ./migration_steps/validation/api_test_data_s3_upload:/validation/api_test_data_s3_upload
      - ./migration_steps/validation/post_migration_db_tasks:/validation/post_migration_db_tasks
      - ./migration_steps/validation/post_migration_tests:/validation/post_migration_tests
      - ./migration_steps/validation/validate_db:/validation/validate_db
      - ./migration_steps/validation/validate.sh:/validation/validate.sh
      - ./migration_steps/shared:/shared
