version: "3.6"

#docker-compose.override.yml is loaded and merged with docker-compose.yml by default when calling docker-compose up.
#This file won't be merged when using docker-compose -f docker-compose.yml up (or using any other compose file).
services:

  load_casrec:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      ENVIRONMENT: development
      CI: $CI
      SIRIUS_ACCOUNT: 288342028542

  validation:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      ENVIRONMENT: development
      CI: $CI
      SIRIUS_ACCOUNT: 288342028542
